[package]
name = "netcore-rs"
version = "0.1.0"
authors = ["<all8up@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
pretty_env_logger = "0.4"
libloading = "0.6"
thiserror = "1"
